apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rh-gitops-midstream/catalog?rev=de003fbfc9b20910b6e1a0ea21b353581bdf7da9
    build.appstudio.redhat.com/commit_sha: de003fbfc9b20910b6e1a0ea21b353581bdf7da9
    build.appstudio.redhat.com/target_branch: main
    pac.test.appstudio.openshift.io/branch: main
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "65389929370"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-mgpmof
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "56531091"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-openshift-gitops-tenant/pipelinerun/catalog-4-20-on-push-g92w9
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: |-
      event == "push" &&  target_branch == "main" &&  (
        "catalog/v4.20/***".pathChanged() ||
        ".tekton/catalog-4-20-push.yaml".pathChanged() ||
        ".tekton/images-mirror-set.yaml".pathChanged() ||
        ".tekton/multi-platform-fbc-image-build.yaml".pathChanged() ||
        ".tekton/tasks/***".pathChanged()
      )
    pac.test.appstudio.openshift.io/original-prname: catalog-4-20-on-push
    pac.test.appstudio.openshift.io/pull-request: "99"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/rh-gitops-midstream/catalog
    pac.test.appstudio.openshift.io/repository: catalog-4-12
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: Rizwana777
    pac.test.appstudio.openshift.io/sha: de003fbfc9b20910b6e1a0ea21b353581bdf7da9
    pac.test.appstudio.openshift.io/sha-title: |-
      chore(release-candidate): update catalog for build v1.19.2-5 (#99)

      Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
    pac.test.appstudio.openshift.io/sha-url: https://github.com/rh-gitops-midstream/catalog/commit/de003fbfc9b20910b6e1a0ea21b353581bdf7da9
    pac.test.appstudio.openshift.io/source-branch: refs/heads/main
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/rh-gitops-midstream/catalog
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: rh-gitops-midstream
    pac.test.appstudio.openshift.io/url-repository: catalog
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2026-03-02T11:52:26Z"}'
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"conforma-catalog-4-20-catalog-4-20-20260302-114101-000":{"lastUpdateTime":"2026-03-02T11:52:59.005666723Z"},"enterprise-contract-catalog-4-20-catalog-4-20-20260302-114101-000":{"lastUpdateTime":"2026-03-02T11:52:45.990658327Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1772451661000"
    test.appstudio.openshift.io/pr-status: merged
    test.appstudio.openshift.io/source-repo-url: https://github.com/rh-gitops-midstream/catalog
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-catalog-4-20","status":"TestPassed","lastUpdateTime":"2026-03-02T11:52:45.990658327Z","details":"Integration
      test passed","startTime":"2026-03-02T11:52:26.393814518Z","completionTime":"2026-03-02T11:52:45.990658327Z","testPipelineRunName":"enterprise-contract-catalog-4-20-48b8g"},{"scenario":"conforma-catalog-4-20","status":"TestPassed","lastUpdateTime":"2026-03-02T11:52:59.005666723Z","details":"Integration
      test passed","startTime":"2026-03-02T11:52:26.424349138Z","completionTime":"2026-03-02T11:52:59.005666723Z","testPipelineRunName":"conforma-catalog-4-20-64kxm"}]'
  creationTimestamp: "2026-03-02T11:52:26Z"
  generation: 1
  labels:
    appstudio.openshift.io/application: catalog-4-20
    appstudio.openshift.io/build-pipelinerun: catalog-4-20-on-push-g92w9
    appstudio.openshift.io/component: catalog-4-20
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "65389929370"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: catalog-4-20-on-push
    pac.test.appstudio.openshift.io/pull-request: "99"
    pac.test.appstudio.openshift.io/repository: catalog-4-12
    pac.test.appstudio.openshift.io/sha: de003fbfc9b20910b6e1a0ea21b353581bdf7da9
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: rh-gitops-midstream
    pac.test.appstudio.openshift.io/url-repository: catalog
    test.appstudio.openshift.io/pipelinerunfinishtime: "1772452341"
    test.appstudio.openshift.io/type: component
  name: catalog-4-20-1175-1184-1192
  namespace: rh-openshift-gitops-tenant
  resourceVersion: "7544289983"
  uid: c2f8ee39-d1be-44a3-9a7c-b64972426a61
spec:
  application: catalog-4-20
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/catalog@sha256:e132c6a1124eea975aeeb1577df0f194d4e3b5f53333533acaebd8284229bc95
    name: catalog-4-20
    source:
      git:
        revision: de003fbfc9b20910b6e1a0ea21b353581bdf7da9
        url: https://github.com/rh-gitops-midstream/catalog
status:
  conditions:
  - lastTransitionTime: "2026-03-02T11:52:46Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2026-03-02T11:52:46Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2026-03-02T11:52:46Z"
    message: Skipping auto-release of the Snapshot because no ReleasePlans have the
      'auto-release' label set to 'true'
    reason: AutoReleased
    status: "True"
    type: AutoReleased
