apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rh-gitops-midstream/catalog?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: "{{revision}}"
    build.appstudio.redhat.com/pull_request_number: "{{pull_request_number}}"
    build.appstudio.redhat.com/target_branch: "{{target_branch}}"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression:
      event == "pull_request" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: operator-catalog-4-12
    appstudio.openshift.io/component: catalog-4-12
    pipelines.appstudio.openshift.io/type: build
  name: catalog-4-12-on-pull-request
  namespace: rh-openshift-gitops-tenant
spec:
  params:
    - name: git-url
      value: "{{source_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/catalog-4-12:on-pr-{{revision}}
    - name: image-expires-after
      value: 5d
    - name: build-platforms
      value:
        - linux/x86_64
    - name: dockerfile
      value: Dockerfile
    - name: path-context
      value: catalog/v4.12
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/rh-gitops-midstream/catalog.git
      - name: revision
        value: main
      - name: pathInRepo
        value: /konflux-ci/pipelines/multi-platform-fbc-image-build.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-catalog-4-12
  workspaces:
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
status: {}
